language: ruby
bnndler_args: --without development --path vendor/bundle
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database kikupon_test'
rvm:
  - 2.0.0
gemfile:
  - Gemfile
env:
  - DB=mysql
branches:
  only:
    - master
